/**
 * augReal.cpp
 * ===========
 * Augmented Reality: reads a video, detects a chessboard pattern in each
 * frame and superimposes a 3-D coordinate axis using the camera intrinsics
 * obtained with calibrate.
 *
 * Usage:
 *   augReal <size> <intrinsics.yml> <videofile>
 *
 *   size           : axis length in board-square units (e.g. 2)
 *   intrinsics.yml : YAML file generated by calibrate
 *   videofile      : path to the video (or 0 for webcam)
 *
 * Example:
 *   ./augReal 2 calibration.yml augreal.mp4
 *
 * Controls:
 *   q / ESC  →  quit
 *   p        →  pause / resume
 *   s        →  save current frame as PNG
 */

#include <opencv2/opencv.hpp>
#include <iostream>
#include <vector>
#include <string>

using namespace std;
using namespace cv;

// ─── draw the three coloured axes ─────────────────────────────────────────────
//
//  origin  → X  (Red)
//  origin  → Y  (Green)
//  origin  → Z  (Blue, pointing out of the board toward the camera)
//
static void drawAxes(Mat &img,
                     const Mat &rvec, const Mat &tvec,
                     const Mat &cam,  const Mat &dist,
                     float size)
{
    // 3-D axis endpoints
    vector<Point3f> pts3d = {
        {0,    0,     0},     // origin
        {size, 0,     0},     // X tip
        {0,    size,  0},     // Y tip
        {0,    0,    -size}   // Z tip (out of board)
    };

    // Step 4 — project onto image plane
    vector<Point2f> pts2d;
    projectPoints(pts3d, rvec, tvec, cam, dist, pts2d);

    Point O  = pts2d[0];
    Point Px = pts2d[1];
    Point Py = pts2d[2];
    Point Pz = pts2d[3];

    const int T = 3;   // line thickness

    // Draw axes using cv::line as required
    line(img, O, Px, Scalar(0,   0, 255), T);   // X  → Red
    line(img, O, Py, Scalar(0, 255,   0), T);   // Y  → Green
    line(img, O, Pz, Scalar(255,   0,   0), T); // Z  → Blue

    // Arrowhead dots
    circle(img, Px, 6, Scalar(0,   0, 255), -1);
    circle(img, Py, 6, Scalar(0, 255,   0), -1);
    circle(img, Pz, 6, Scalar(255,   0,   0), -1);

    // Labels
    putText(img, "X", Px + Point(8, 0),  FONT_HERSHEY_SIMPLEX, 0.8, Scalar(0,   0, 255), 2);
    putText(img, "Y", Py + Point(8, 0),  FONT_HERSHEY_SIMPLEX, 0.8, Scalar(0, 255,   0), 2);
    putText(img, "Z", Pz + Point(8, 0),  FONT_HERSHEY_SIMPLEX, 0.8, Scalar(255,   0,   0), 2);
}

// ─── main ─────────────────────────────────────────────────────────────────────
int main(int argc, char **argv)
{
    if (argc < 4) {
        cerr << "Usage: " << argv[0]
             << " <size> <intrinsics.yml> <videofile>\n"
             << "Example: ./augReal 2 calibration.yml augreal.mp4\n";
        return 1;
    }

    // ── Parse and validate arguments ─────────────────────────────────────────
    const float  axisSize = (float)atof(argv[1]);
    const string ymlPath  = argv[2];
    const string vidStr   = argv[3];

    if (axisSize <= 0) {
        cerr << "ERROR: <size> must be a positive number (got '" << vidStr << "')\n";
        return 1;
    }

    // ── Load intrinsics ───────────────────────────────────────────────────────
    FileStorage fs(ymlPath, FileStorage::READ);
    if (!fs.isOpened()) {
        cerr << "ERROR: cannot open '" << ymlPath << "'\n"; return 1; }

    Mat cameraMatrix, distCoeffs;
    fs["cameraMatrix"] >> cameraMatrix;
    fs["distCoeffs"]   >> distCoeffs;
    int BOARD_W = (int)fs["board_width"];
    int BOARD_H = (int)fs["board_height"];
    fs.release();

    if (cameraMatrix.empty()) {
        cerr << "ERROR: 'cameraMatrix' not found in '" << ymlPath << "'\n"; return 1; }
    if (distCoeffs.empty()) {
        cerr << "ERROR: 'distCoeffs' not found in '" << ymlPath << "'\n"; return 1; }
    if (BOARD_W <= 0) BOARD_W = 7;
    if (BOARD_H <= 0) BOARD_H = 5;

    const Size boardSz(BOARD_W, BOARD_H);
    cout << "Loaded '" << ymlPath << "'  — board " << BOARD_W << "x" << BOARD_H << "\n";
    cout << "Axis size: " << axisSize << " board units\n";
    cout << "Controls: [q/ESC] quit   [p] pause   [s] save frame\n\n";

    // 3-D object points
    vector<Point3f> objp;
    for (int r = 0; r < BOARD_H; r++)
        for (int c = 0; c < BOARD_W; c++)
            objp.push_back(Point3f((float)c, (float)r, 0.f));

    const TermCriteria criteria(
        TermCriteria::EPS + TermCriteria::MAX_ITER, 30, 0.001);

    // ── Open video (or webcam if argument is a number) ────────────────────────
    VideoCapture video;
    // Check if vidStr is a pure integer (camera index)
    bool isCamera = !vidStr.empty();
    for (char c : vidStr) if (!isdigit(c)) { isCamera = false; break; }

    if (isCamera)
        video.open(atoi(vidStr.c_str()));
    else
        video.open(vidStr);

    if (!video.isOpened()) {
        cerr << "ERROR: cannot open '" << vidStr << "'\n"; return 1; }

    double fps     = video.get(CAP_PROP_FPS);
    int    nFrames = (int)video.get(CAP_PROP_FRAME_COUNT);
    if (fps <= 0) fps = 30;
    cout << "Video: " << vidStr
         << "  FPS=" << fps << "  frames=" << nFrames << "\n\n";

    bool paused  = false;
    int  frameN  = 0;
    int  saveN   = 0;
    Mat  image;

    // Main loop — mirrors professor's while(video.grab()) pattern
    while (video.grab())
    {
        video.retrieve(image);
        frameN++;

        Mat display = image.clone();
        Mat gray;
        cvtColor(image, gray, COLOR_BGR2GRAY);

        vector<Point2f> corners;

        // Step 1 — detect the board
        bool found = findChessboardCorners(
            gray, boardSz, corners,
            CALIB_CB_ADAPTIVE_THRESH | CALIB_CB_NORMALIZE_IMAGE
        );

        string msg;
        Scalar msgColor;

        if (found) {
            // Step 2 — refine corners (cornerSubPix)
            cornerSubPix(gray, corners, Size(11, 11), Size(-1, -1), criteria);

            // Step 3 — estimate pose (solvePnP)
            Mat rvec, tvec;
            bool ok = solvePnP(objp, corners, cameraMatrix, distCoeffs, rvec, tvec);

            if (ok) {
                // Step 4 — draw 3D axes (projectPoints + line)
                drawAxes(display, rvec, tvec, cameraMatrix, distCoeffs, axisSize);
                msg      = "[" + to_string(frameN) + "] Board OK | Pose OK";
                msgColor = Scalar(50, 220, 50);
            } else {
                msg      = "[" + to_string(frameN) + "] Board found | solvePnP FAILED";
                msgColor = Scalar(0, 165, 255);
            }
        } else {
            msg      = "[" + to_string(frameN) + "] Board NOT detected";
            msgColor = Scalar(50, 50, 220);
        }

        // HUD overlay
        rectangle(display, Point(0, 0), Point(450, 30), Scalar(0, 0, 0), -1);
        putText(display, msg, Point(5, 22), FONT_HERSHEY_SIMPLEX, 0.6, msgColor, 2);
        if (paused)
            putText(display, "PAUSED", Point(5, display.rows - 15),
                    FONT_HERSHEY_SIMPLEX, 0.8, Scalar(0, 220, 220), 2);

        imshow("image", display);

        int wait = paused ? 0 : max(1, (int)(1000.0 / fps));
        int key  = waitKey(wait) & 0xFF;

        if (key == 'q' || key == 27)           break;
        else if (key == 'p') {
            paused = !paused;
            cout << (paused ? "Paused\n" : "Resumed\n");
            if (paused) {
                // When paused, keep showing the same frame
                while (true) {
                    imshow("image", display);
                    int k = waitKey(30) & 0xFF;
                    if (k == 'p') { paused = false; cout << "Resumed\n"; break; }
                    if (k == 'q' || k == 27) { goto done; }
                    if (k == 's') {
                        string fn = "output_" + to_string(saveN++) + ".png";
                        imwrite(fn, display);
                        cout << "Saved " << fn << "\n";
                    }
                }
            }
        }
        else if (key == 's') {
            string fn = "output_" + to_string(saveN++) + ".png";
            imwrite(fn, display);
            cout << "Saved " << fn << "\n";
        }
    }

    done:
    video.release();
    destroyAllWindows();
    return 0;
}
